name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set image tag
      id: tag
      run: echo "::set-output name=tag::$(date +%s)"
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag itransfer:${{ steps.tag.outputs.tag }}
    
    - name: Run tests
      run: |
        docker run --rm itransfer:${{ steps.tag.outputs.tag }} dotnet test
